// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commands.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimCommand = `-- name: ClaimCommand :one
UPDATE command_inbox
SET locked_until = now() + interval '15 seconds',
    claim_token = $2
WHERE command_id = $1
  AND state = 'received'
  AND result IS NULL
  AND (locked_until IS NULL OR locked_until < now())
RETURNING command_id, tenant_id, command_type, request, state, result, http_status, locked_until, claim_token, dispatched_at, created_at, completed_at
`

type ClaimCommandParams struct {
	CommandID  pgtype.UUID `json:"command_id"`
	ClaimToken pgtype.UUID `json:"claim_token"`
}

func (q *Queries) ClaimCommand(ctx context.Context, arg ClaimCommandParams) (CommandInbox, error) {
	row := q.db.QueryRow(ctx, claimCommand, arg.CommandID, arg.ClaimToken)
	var i CommandInbox
	err := row.Scan(
		&i.CommandID,
		&i.TenantID,
		&i.CommandType,
		&i.Request,
		&i.State,
		&i.Result,
		&i.HttpStatus,
		&i.LockedUntil,
		&i.ClaimToken,
		&i.DispatchedAt,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeCommand = `-- name: CompleteCommand :execrows
UPDATE command_inbox
SET state = 'completed',
    result = $2,
    http_status = $3,
    locked_until = NULL,
    claim_token = NULL,
    completed_at = now()
WHERE command_id = $1
  AND claim_token = $4
  AND state IN ('received', 'dispatching')
`

type CompleteCommandParams struct {
	CommandID  pgtype.UUID `json:"command_id"`
	Result     []byte      `json:"result"`
	HttpStatus pgtype.Int4 `json:"http_status"`
	ClaimToken pgtype.UUID `json:"claim_token"`
}

func (q *Queries) CompleteCommand(ctx context.Context, arg CompleteCommandParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCommand,
		arg.CommandID,
		arg.Result,
		arg.HttpStatus,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCommand = `-- name: GetCommand :one
SELECT command_id, tenant_id, command_type, request, state, result, http_status, locked_until, claim_token, dispatched_at, created_at, completed_at
FROM command_inbox
WHERE command_id = $1
`

func (q *Queries) GetCommand(ctx context.Context, commandID pgtype.UUID) (CommandInbox, error) {
	row := q.db.QueryRow(ctx, getCommand, commandID)
	var i CommandInbox
	err := row.Scan(
		&i.CommandID,
		&i.TenantID,
		&i.CommandType,
		&i.Request,
		&i.State,
		&i.Result,
		&i.HttpStatus,
		&i.LockedUntil,
		&i.ClaimToken,
		&i.DispatchedAt,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertCommand = `-- name: InsertCommand :execrows
INSERT INTO command_inbox (command_id, command_type, request)
VALUES ($1, $2, $3)
ON CONFLICT (command_id) DO NOTHING
`

type InsertCommandParams struct {
	CommandID   pgtype.UUID `json:"command_id"`
	CommandType string      `json:"command_type"`
	Request     []byte      `json:"request"`
}

func (q *Queries) InsertCommand(ctx context.Context, arg InsertCommandParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCommand, arg.CommandID, arg.CommandType, arg.Request)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markCommandDispatching = `-- name: MarkCommandDispatching :one
UPDATE command_inbox
SET state = 'dispatching',
    dispatched_at = now(),
    locked_until = NULL
WHERE command_id = $1
  AND state = 'received'
  AND claim_token = $2
RETURNING command_id, tenant_id, command_type, request, state, result, http_status, locked_until, claim_token, dispatched_at, created_at, completed_at
`

type MarkCommandDispatchingParams struct {
	CommandID  pgtype.UUID `json:"command_id"`
	ClaimToken pgtype.UUID `json:"claim_token"`
}

func (q *Queries) MarkCommandDispatching(ctx context.Context, arg MarkCommandDispatchingParams) (CommandInbox, error) {
	row := q.db.QueryRow(ctx, markCommandDispatching, arg.CommandID, arg.ClaimToken)
	var i CommandInbox
	err := row.Scan(
		&i.CommandID,
		&i.TenantID,
		&i.CommandType,
		&i.Request,
		&i.State,
		&i.Result,
		&i.HttpStatus,
		&i.LockedUntil,
		&i.ClaimToken,
		&i.DispatchedAt,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
