// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CommandInbox struct {
	CommandID    pgtype.UUID        `json:"command_id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	CommandType  string             `json:"command_type"`
	Request      []byte             `json:"request"`
	State        string             `json:"state"`
	Result       []byte             `json:"result"`
	HttpStatus   pgtype.Int4        `json:"http_status"`
	LockedUntil  pgtype.Timestamptz `json:"locked_until"`
	ClaimToken   pgtype.UUID        `json:"claim_token"`
	DispatchedAt pgtype.Timestamptz `json:"dispatched_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type Outbox struct {
	EventID     pgtype.UUID        `json:"event_id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	SessionRef  pgtype.UUID        `json:"session_ref"`
	Sequence    int64              `json:"sequence"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Attempts    int32              `json:"attempts"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

type Session struct {
	SessionRef        pgtype.UUID        `json:"session_ref"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	StartCommandID    pgtype.UUID        `json:"start_command_id"`
	StopCommandID     pgtype.UUID        `json:"stop_command_id"`
	ChargerID         string             `json:"charger_id"`
	ConnectorID       int32              `json:"connector_id"`
	IDTag             string             `json:"id_tag"`
	State             string             `json:"state"`
	OcppTransactionID pgtype.Int4        `json:"ocpp_transaction_id"`
	LimitEnergyWh     int64              `json:"limit_energy_wh"`
	LimitDurationS    int32              `json:"limit_duration_s"`
	MeterStartWh      pgtype.Int8        `json:"meter_start_wh"`
	MeterStopWh       pgtype.Int8        `json:"meter_stop_wh"`
	LastEnergyWh      pgtype.Int8        `json:"last_energy_wh"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	StoppedAt         pgtype.Timestamptz `json:"stopped_at"`
	StopReason        pgtype.Text        `json:"stop_reason"`
	StopSource        pgtype.Text        `json:"stop_source"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type SessionEventSequence struct {
	SessionRef   pgtype.UUID `json:"session_ref"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	LastSequence int64       `json:"last_sequence"`
}
