// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendOutboxEvent = `-- name: AppendOutboxEvent :one
WITH seq AS (
    INSERT INTO session_event_sequences (session_ref, last_sequence)
    VALUES ($1, 1)
    ON CONFLICT (session_ref)
    DO UPDATE SET last_sequence = session_event_sequences.last_sequence + 1
    RETURNING last_sequence
)
INSERT INTO outbox (session_ref, sequence, event_type, payload, occurred_at)
SELECT $1, last_sequence, $2, $3, $4
FROM seq
RETURNING event_id, tenant_id, session_ref, sequence, event_type, payload, occurred_at, created_at, published_at, attempts, locked_until
`

type AppendOutboxEventParams struct {
	SessionRef pgtype.UUID        `json:"session_ref"`
	EventType  string             `json:"event_type"`
	Payload    []byte             `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) AppendOutboxEvent(ctx context.Context, arg AppendOutboxEventParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, appendOutboxEvent,
		arg.SessionRef,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
	)
	var i Outbox
	err := row.Scan(
		&i.EventID,
		&i.TenantID,
		&i.SessionRef,
		&i.Sequence,
		&i.EventType,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Attempts,
		&i.LockedUntil,
	)
	return i, err
}

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
WITH candidates AS (
    SELECT event_id, session_ref, sequence
    FROM outbox AS pending
    WHERE published_at IS NULL
      AND (locked_until IS NULL OR locked_until < now())
      AND NOT EXISTS (
          SELECT 1
          FROM outbox AS earlier
          WHERE earlier.session_ref = pending.session_ref
            AND earlier.sequence < pending.sequence
            AND earlier.published_at IS NULL
      )
    ORDER BY session_ref, sequence
    FOR UPDATE SKIP LOCKED
),
heads AS (
    SELECT DISTINCT ON (session_ref) event_id
    FROM candidates
    ORDER BY session_ref, sequence
    LIMIT $1
)
UPDATE outbox
SET locked_until = now() + interval '30 seconds',
    attempts = attempts + 1
WHERE event_id IN (SELECT event_id FROM heads)
RETURNING event_id, tenant_id, session_ref, sequence, event_type, payload, occurred_at, created_at, published_at, attempts, locked_until
`

func (q *Queries) ClaimOutboxBatch(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.EventID,
			&i.TenantID,
			&i.SessionRef,
			&i.Sequence,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Attempts,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :execrows
UPDATE outbox
SET published_at = now(),
    locked_until = NULL
WHERE event_id = $1
  AND published_at IS NULL
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, eventID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxPublished, eventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseOutbox = `-- name: ReleaseOutbox :exec
UPDATE outbox
SET locked_until = NULL
WHERE event_id = $1
  AND published_at IS NULL
`

func (q *Queries) ReleaseOutbox(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseOutbox, eventID)
	return err
}
