// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateSession(ctx context.Context, arg ActivateSessionParams) (Session, error)
	AppendOutboxEvent(ctx context.Context, arg AppendOutboxEventParams) (Outbox, error)
	ClaimCommand(ctx context.Context, arg ClaimCommandParams) (CommandInbox, error)
	ClaimOutboxBatch(ctx context.Context, limit int32) ([]Outbox, error)
	CompleteCommand(ctx context.Context, arg CompleteCommandParams) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Events behind a dead event in the same session can never be accepted in order,
	// so they are dead too. Returns how many were swept.
	DeadLetterBlockedOutbox(ctx context.Context) (int64, error)
	FailSession(ctx context.Context, arg FailSessionParams) (int64, error)
	GetCommand(ctx context.Context, commandID pgtype.UUID) (CommandInbox, error)
	GetSession(ctx context.Context, sessionRef pgtype.UUID) (Session, error)
	GetSessionByTransaction(ctx context.Context, arg GetSessionByTransactionParams) (Session, error)
	GetSessionForStart(ctx context.Context, arg GetSessionForStartParams) (Session, error)
	InsertCommand(ctx context.Context, arg InsertCommandParams) (int64, error)
	ListRecoverableSessions(ctx context.Context) ([]Session, error)
	MarkCommandDispatching(ctx context.Context, arg MarkCommandDispatchingParams) (CommandInbox, error)
	MarkOutboxPublished(ctx context.Context, eventID pgtype.UUID) (int64, error)
	MarkSessionStopping(ctx context.Context, arg MarkSessionStoppingParams) (Session, error)
	RecordMeterValue(ctx context.Context, arg RecordMeterValueParams) (Session, error)
	// The platform refused this event. Count it, back off, and mark it dead once it
	// has been refused max_rejections times. Returns whether the event is now dead.
	RejectOutbox(ctx context.Context, arg RejectOutboxParams) (bool, error)
	// A failure that says nothing about the event itself (platform down, timeout,
	// 5xx, bad signature): try again later, with a delay that doubles up to a minute.
	ReleaseOutbox(ctx context.Context, arg ReleaseOutboxParams) error
	RestoreLimitSessionActive(ctx context.Context, arg RestoreLimitSessionActiveParams) (int64, error)
	RestoreSessionActive(ctx context.Context, sessionRef pgtype.UUID) (int64, error)
	StopSession(ctx context.Context, arg StopSessionParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
