// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateSession(ctx context.Context, arg ActivateSessionParams) (Session, error)
	ClaimCommand(ctx context.Context, arg ClaimCommandParams) (CommandInbox, error)
	CompleteCommand(ctx context.Context, arg CompleteCommandParams) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	FailSession(ctx context.Context, arg FailSessionParams) (int64, error)
	GetCommand(ctx context.Context, commandID pgtype.UUID) (CommandInbox, error)
	GetSession(ctx context.Context, sessionRef pgtype.UUID) (Session, error)
	GetSessionByTransaction(ctx context.Context, arg GetSessionByTransactionParams) (Session, error)
	GetSessionForStart(ctx context.Context, arg GetSessionForStartParams) (Session, error)
	InsertCommand(ctx context.Context, arg InsertCommandParams) (int64, error)
	ListRecoverableSessions(ctx context.Context) ([]Session, error)
	MarkCommandDispatching(ctx context.Context, arg MarkCommandDispatchingParams) (CommandInbox, error)
	MarkSessionStopping(ctx context.Context, arg MarkSessionStoppingParams) (Session, error)
	RecordMeterValue(ctx context.Context, arg RecordMeterValueParams) (Session, error)
	RestoreLimitSessionActive(ctx context.Context, arg RestoreLimitSessionActiveParams) (int64, error)
	RestoreSessionActive(ctx context.Context, sessionRef pgtype.UUID) (int64, error)
	StopSession(ctx context.Context, arg StopSessionParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
