// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateSession = `-- name: ActivateSession :one
UPDATE sessions
SET state = 'active',
    ocpp_transaction_id = nextval('ocpp_transaction_ids'),
    meter_start_wh = $2,
    last_energy_wh = $2,
    started_at = $3,
    updated_at = now()
WHERE session_ref = $1
  AND state = 'start_requested'
RETURNING session_ref, tenant_id, start_command_id, stop_command_id, charger_id, connector_id, id_tag, state, ocpp_transaction_id, limit_energy_wh, limit_duration_s, meter_start_wh, meter_stop_wh, last_energy_wh, started_at, stopped_at, stop_reason, stop_source, created_at, updated_at
`

type ActivateSessionParams struct {
	SessionRef   pgtype.UUID        `json:"session_ref"`
	MeterStartWh pgtype.Int8        `json:"meter_start_wh"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) ActivateSession(ctx context.Context, arg ActivateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, activateSession, arg.SessionRef, arg.MeterStartWh, arg.StartedAt)
	var i Session
	err := row.Scan(
		&i.SessionRef,
		&i.TenantID,
		&i.StartCommandID,
		&i.StopCommandID,
		&i.ChargerID,
		&i.ConnectorID,
		&i.IDTag,
		&i.State,
		&i.OcppTransactionID,
		&i.LimitEnergyWh,
		&i.LimitDurationS,
		&i.MeterStartWh,
		&i.MeterStopWh,
		&i.LastEnergyWh,
		&i.StartedAt,
		&i.StoppedAt,
		&i.StopReason,
		&i.StopSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    session_ref,
    start_command_id,
    charger_id,
    connector_id,
    id_tag,
    state,
    limit_energy_wh,
    limit_duration_s
)
VALUES ($1, $2, $3, $4, $5, 'start_requested', $6, $7)
RETURNING session_ref, tenant_id, start_command_id, stop_command_id, charger_id, connector_id, id_tag, state, ocpp_transaction_id, limit_energy_wh, limit_duration_s, meter_start_wh, meter_stop_wh, last_energy_wh, started_at, stopped_at, stop_reason, stop_source, created_at, updated_at
`

type CreateSessionParams struct {
	SessionRef     pgtype.UUID `json:"session_ref"`
	StartCommandID pgtype.UUID `json:"start_command_id"`
	ChargerID      string      `json:"charger_id"`
	ConnectorID    int32       `json:"connector_id"`
	IDTag          string      `json:"id_tag"`
	LimitEnergyWh  int64       `json:"limit_energy_wh"`
	LimitDurationS int32       `json:"limit_duration_s"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.SessionRef,
		arg.StartCommandID,
		arg.ChargerID,
		arg.ConnectorID,
		arg.IDTag,
		arg.LimitEnergyWh,
		arg.LimitDurationS,
	)
	var i Session
	err := row.Scan(
		&i.SessionRef,
		&i.TenantID,
		&i.StartCommandID,
		&i.StopCommandID,
		&i.ChargerID,
		&i.ConnectorID,
		&i.IDTag,
		&i.State,
		&i.OcppTransactionID,
		&i.LimitEnergyWh,
		&i.LimitDurationS,
		&i.MeterStartWh,
		&i.MeterStopWh,
		&i.LastEnergyWh,
		&i.StartedAt,
		&i.StoppedAt,
		&i.StopReason,
		&i.StopSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failSession = `-- name: FailSession :execrows
UPDATE sessions
SET state = 'failed',
    stop_reason = $2,
    updated_at = now()
WHERE session_ref = $1
  AND state = 'start_requested'
`

type FailSessionParams struct {
	SessionRef pgtype.UUID `json:"session_ref"`
	StopReason pgtype.Text `json:"stop_reason"`
}

func (q *Queries) FailSession(ctx context.Context, arg FailSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, failSession, arg.SessionRef, arg.StopReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSession = `-- name: GetSession :one
SELECT session_ref, tenant_id, start_command_id, stop_command_id, charger_id, connector_id, id_tag, state, ocpp_transaction_id, limit_energy_wh, limit_duration_s, meter_start_wh, meter_stop_wh, last_energy_wh, started_at, stopped_at, stop_reason, stop_source, created_at, updated_at
FROM sessions
WHERE session_ref = $1
`

func (q *Queries) GetSession(ctx context.Context, sessionRef pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, sessionRef)
	var i Session
	err := row.Scan(
		&i.SessionRef,
		&i.TenantID,
		&i.StartCommandID,
		&i.StopCommandID,
		&i.ChargerID,
		&i.ConnectorID,
		&i.IDTag,
		&i.State,
		&i.OcppTransactionID,
		&i.LimitEnergyWh,
		&i.LimitDurationS,
		&i.MeterStartWh,
		&i.MeterStopWh,
		&i.LastEnergyWh,
		&i.StartedAt,
		&i.StoppedAt,
		&i.StopReason,
		&i.StopSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTransaction = `-- name: GetSessionByTransaction :one
SELECT session_ref, tenant_id, start_command_id, stop_command_id, charger_id, connector_id, id_tag, state, ocpp_transaction_id, limit_energy_wh, limit_duration_s, meter_start_wh, meter_stop_wh, last_energy_wh, started_at, stopped_at, stop_reason, stop_source, created_at, updated_at
FROM sessions
WHERE charger_id = $1
  AND ocpp_transaction_id = $2
`

type GetSessionByTransactionParams struct {
	ChargerID         string      `json:"charger_id"`
	OcppTransactionID pgtype.Int4 `json:"ocpp_transaction_id"`
}

func (q *Queries) GetSessionByTransaction(ctx context.Context, arg GetSessionByTransactionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTransaction, arg.ChargerID, arg.OcppTransactionID)
	var i Session
	err := row.Scan(
		&i.SessionRef,
		&i.TenantID,
		&i.StartCommandID,
		&i.StopCommandID,
		&i.ChargerID,
		&i.ConnectorID,
		&i.IDTag,
		&i.State,
		&i.OcppTransactionID,
		&i.LimitEnergyWh,
		&i.LimitDurationS,
		&i.MeterStartWh,
		&i.MeterStopWh,
		&i.LastEnergyWh,
		&i.StartedAt,
		&i.StoppedAt,
		&i.StopReason,
		&i.StopSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionForStart = `-- name: GetSessionForStart :one
SELECT session_ref, tenant_id, start_command_id, stop_command_id, charger_id, connector_id, id_tag, state, ocpp_transaction_id, limit_energy_wh, limit_duration_s, meter_start_wh, meter_stop_wh, last_energy_wh, started_at, stopped_at, stop_reason, stop_source, created_at, updated_at
FROM sessions
WHERE charger_id = $1
  AND connector_id = $2
  AND id_tag = $3
  AND state IN ('start_requested', 'active')
ORDER BY created_at DESC
LIMIT 1
`

type GetSessionForStartParams struct {
	ChargerID   string `json:"charger_id"`
	ConnectorID int32  `json:"connector_id"`
	IDTag       string `json:"id_tag"`
}

func (q *Queries) GetSessionForStart(ctx context.Context, arg GetSessionForStartParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionForStart, arg.ChargerID, arg.ConnectorID, arg.IDTag)
	var i Session
	err := row.Scan(
		&i.SessionRef,
		&i.TenantID,
		&i.StartCommandID,
		&i.StopCommandID,
		&i.ChargerID,
		&i.ConnectorID,
		&i.IDTag,
		&i.State,
		&i.OcppTransactionID,
		&i.LimitEnergyWh,
		&i.LimitDurationS,
		&i.MeterStartWh,
		&i.MeterStopWh,
		&i.LastEnergyWh,
		&i.StartedAt,
		&i.StoppedAt,
		&i.StopReason,
		&i.StopSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecoverableSessions = `-- name: ListRecoverableSessions :many
SELECT session_ref, tenant_id, start_command_id, stop_command_id, charger_id, connector_id, id_tag, state, ocpp_transaction_id, limit_energy_wh, limit_duration_s, meter_start_wh, meter_stop_wh, last_energy_wh, started_at, stopped_at, stop_reason, stop_source, created_at, updated_at
FROM sessions
WHERE state = 'active'
   OR (state = 'stopping' AND stop_command_id IS NULL)
ORDER BY started_at
`

func (q *Queries) ListRecoverableSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, listRecoverableSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.SessionRef,
			&i.TenantID,
			&i.StartCommandID,
			&i.StopCommandID,
			&i.ChargerID,
			&i.ConnectorID,
			&i.IDTag,
			&i.State,
			&i.OcppTransactionID,
			&i.LimitEnergyWh,
			&i.LimitDurationS,
			&i.MeterStartWh,
			&i.MeterStopWh,
			&i.LastEnergyWh,
			&i.StartedAt,
			&i.StoppedAt,
			&i.StopReason,
			&i.StopSource,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionStopping = `-- name: MarkSessionStopping :one
UPDATE sessions
SET state = 'stopping',
    stop_source = $2,
    stop_command_id = $3,
    updated_at = now()
WHERE session_ref = $1
  AND state = 'active'
RETURNING session_ref, tenant_id, start_command_id, stop_command_id, charger_id, connector_id, id_tag, state, ocpp_transaction_id, limit_energy_wh, limit_duration_s, meter_start_wh, meter_stop_wh, last_energy_wh, started_at, stopped_at, stop_reason, stop_source, created_at, updated_at
`

type MarkSessionStoppingParams struct {
	SessionRef    pgtype.UUID `json:"session_ref"`
	StopSource    pgtype.Text `json:"stop_source"`
	StopCommandID pgtype.UUID `json:"stop_command_id"`
}

func (q *Queries) MarkSessionStopping(ctx context.Context, arg MarkSessionStoppingParams) (Session, error) {
	row := q.db.QueryRow(ctx, markSessionStopping, arg.SessionRef, arg.StopSource, arg.StopCommandID)
	var i Session
	err := row.Scan(
		&i.SessionRef,
		&i.TenantID,
		&i.StartCommandID,
		&i.StopCommandID,
		&i.ChargerID,
		&i.ConnectorID,
		&i.IDTag,
		&i.State,
		&i.OcppTransactionID,
		&i.LimitEnergyWh,
		&i.LimitDurationS,
		&i.MeterStartWh,
		&i.MeterStopWh,
		&i.LastEnergyWh,
		&i.StartedAt,
		&i.StoppedAt,
		&i.StopReason,
		&i.StopSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordMeterValue = `-- name: RecordMeterValue :one
UPDATE sessions
SET last_energy_wh = $3,
    updated_at = now()
WHERE charger_id = $1
  AND ocpp_transaction_id = $2
  AND state IN ('active', 'stopping')
  AND $3 >= meter_start_wh
  AND (last_energy_wh IS NULL OR $3 >= last_energy_wh)
RETURNING session_ref, tenant_id, start_command_id, stop_command_id, charger_id, connector_id, id_tag, state, ocpp_transaction_id, limit_energy_wh, limit_duration_s, meter_start_wh, meter_stop_wh, last_energy_wh, started_at, stopped_at, stop_reason, stop_source, created_at, updated_at
`

type RecordMeterValueParams struct {
	ChargerID         string      `json:"charger_id"`
	OcppTransactionID pgtype.Int4 `json:"ocpp_transaction_id"`
	LastEnergyWh      pgtype.Int8 `json:"last_energy_wh"`
}

func (q *Queries) RecordMeterValue(ctx context.Context, arg RecordMeterValueParams) (Session, error) {
	row := q.db.QueryRow(ctx, recordMeterValue, arg.ChargerID, arg.OcppTransactionID, arg.LastEnergyWh)
	var i Session
	err := row.Scan(
		&i.SessionRef,
		&i.TenantID,
		&i.StartCommandID,
		&i.StopCommandID,
		&i.ChargerID,
		&i.ConnectorID,
		&i.IDTag,
		&i.State,
		&i.OcppTransactionID,
		&i.LimitEnergyWh,
		&i.LimitDurationS,
		&i.MeterStartWh,
		&i.MeterStopWh,
		&i.LastEnergyWh,
		&i.StartedAt,
		&i.StoppedAt,
		&i.StopReason,
		&i.StopSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restoreLimitSessionActive = `-- name: RestoreLimitSessionActive :execrows
UPDATE sessions
SET state = 'active',
    stop_source = NULL,
    updated_at = now()
WHERE session_ref = $1
  AND state = 'stopping'
  AND stop_command_id IS NULL
  AND stop_source = $2
`

type RestoreLimitSessionActiveParams struct {
	SessionRef pgtype.UUID `json:"session_ref"`
	StopSource pgtype.Text `json:"stop_source"`
}

func (q *Queries) RestoreLimitSessionActive(ctx context.Context, arg RestoreLimitSessionActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreLimitSessionActive, arg.SessionRef, arg.StopSource)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreSessionActive = `-- name: RestoreSessionActive :execrows
UPDATE sessions
SET state = 'active',
    stop_source = NULL,
    stop_command_id = NULL,
    updated_at = now()
WHERE session_ref = $1
  AND state = 'stopping'
`

func (q *Queries) RestoreSessionActive(ctx context.Context, sessionRef pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreSessionActive, sessionRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stopSession = `-- name: StopSession :one
UPDATE sessions
SET state = 'stopped',
    meter_stop_wh = $3,
    last_energy_wh = $3,
    stopped_at = $4,
    stop_reason = $5,
    updated_at = now()
WHERE charger_id = $1
  AND ocpp_transaction_id = $2
  AND state IN ('active', 'stopping')
  AND $3 >= COALESCE(last_energy_wh, meter_start_wh)
RETURNING session_ref, tenant_id, start_command_id, stop_command_id, charger_id, connector_id, id_tag, state, ocpp_transaction_id, limit_energy_wh, limit_duration_s, meter_start_wh, meter_stop_wh, last_energy_wh, started_at, stopped_at, stop_reason, stop_source, created_at, updated_at
`

type StopSessionParams struct {
	ChargerID         string             `json:"charger_id"`
	OcppTransactionID pgtype.Int4        `json:"ocpp_transaction_id"`
	MeterStopWh       pgtype.Int8        `json:"meter_stop_wh"`
	StoppedAt         pgtype.Timestamptz `json:"stopped_at"`
	StopReason        pgtype.Text        `json:"stop_reason"`
}

func (q *Queries) StopSession(ctx context.Context, arg StopSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, stopSession,
		arg.ChargerID,
		arg.OcppTransactionID,
		arg.MeterStopWh,
		arg.StoppedAt,
		arg.StopReason,
	)
	var i Session
	err := row.Scan(
		&i.SessionRef,
		&i.TenantID,
		&i.StartCommandID,
		&i.StopCommandID,
		&i.ChargerID,
		&i.ConnectorID,
		&i.IDTag,
		&i.State,
		&i.OcppTransactionID,
		&i.LimitEnergyWh,
		&i.LimitDurationS,
		&i.MeterStartWh,
		&i.MeterStopWh,
		&i.LastEnergyWh,
		&i.StartedAt,
		&i.StoppedAt,
		&i.StopReason,
		&i.StopSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
