default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV.fetch("DATABASE_URL") %>

development:
  <<: *default

test:
  <<: *default
  # db:prepare seeds a newly created primary database. Keep the test database empty.
  seeds: false

production:
  <<: *default
